[package]
name = "ratelimit_meter"
version = "2.0.1-dev"
authors = ["Andreas Fuchs <asf@boinkor.net>"]
license = "MIT"
homepage = "https://github.com/antifuchs/ratelimit_meter"
repository = "https://github.com/antifuchs/ratelimit_meter.git"
readme = "README.md"
description = "A leaky-bucket-as-a-meter rate-limiting implementation in Rust"
documentation = "https://docs.rs/ratelimit_meter"

[badges]
travis-ci = { repository = "antifuchs/ratelimit_meter", branch = "master" }
maintenance = { status = "passively-maintained" }

[dependencies]
failure = "0.1.1"
failure_derive = "0.1.1"

[dev_dependencies]
libc = "0.2.41"

[package.metadata.release]
sign-commit = false
upload-doc = false
pre-release-commit-message = "Release {{version}} ğŸ‰ğŸ‰"
pro-release-commit-message = "Start next development iteration {{version}}"
tag-message = "Release {{prefix}}{{version}}"
dev-version-ext = "dev"
tag-prefix = "v"
